import React from "react";
import axios from "axios";
import nookies from "nookies";
import NavBar from "../../components/navigation/NavBar";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import Head from "next/head";
import { Typography, Box, Button } from "@mui/material";
import { GetServerSideProps } from "next";

// export default async function handler(req, res) {
//   const params = req.query.
//   console.log(params);
//   res.status(200).json(params);
// }

const Users = ({ users, id }) => {
  return (
    <>
      <Head>
        <title>ID - Development Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Box
        sx={{
          marginTop: 2,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        <Typography variant="h3">User {id}</Typography>
        <div>
          {users?.map((user) => (
            <div key={user.id}>
              <h3>
                Username: <b>{user.username}</b>
              </h3>
              <p>
                First Name: <b>{user.firstName}</b>
              </p>
              <p>
                Middle Name: <b>{user.middleName || "NA"} </b>
              </p>
              <p>
                Last Name: <b>{user.lastName}</b>
              </p>
              <p>
                Email: <b>{user.email}</b>
              </p>
              <p>
                Contact: <b>{user.phone}</b>
              </p>
              <hr />
            </div>
          ))}
        </div>
        <Link href={"/profile"}>Back</Link>
      </Box>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = nookies.get(ctx);
  const { params } = ctx;
  const { id } = params;
  console.log(id);
  let users = null;
  if (cookies?.jwt) {
    try {
      const { data } = await axios.get(
        `https://6371e259025414c637002627.mockapi.io/api/fiddle/users?id=${id}`
      );
      users = data;
      //console.log(data);
    } catch (e) {
      console.log(e);
    }
  }

  if (
    cookies?.LoginStatus === "false" ||
    !cookies?.LoginStatus ||
    !cookies?.jwt
  ) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }

  return {
    props: { users, id },
  };
};

export default Users;
