import React from "react";
import axios from "axios";
import nookies from "nookies";
import Head from "next/head";
import { UserProfile } from "../../components/form-fields/UserProfile";
import NavBar from "../../components/navigation/NavBar";
import { useRouter } from "next/router";
import Link from "next/link";

interface Inputs {
  users: {
    username: string;
    password: string;
    confirm: string;
    firstName: string;
    middleName: string;
    lastName: string;
    email: string;
    phone: string;
  };
}

const Profile = ({ users }: Inputs) => {
  const router = useRouter();
  const id = router.query.id as string;
  return (
    <>
      <Head>
        <title>Profile - Development Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Link href={`/profile/${id}`}></Link>
      <UserProfile users={users} />
    </>
  );
};

export const getServerSideProps = async (ctx: any) => {
  const cookies = nookies.get(ctx);
  let users = null;
  if (cookies?.jwt) {
    try {
      const { data } = await axios.get(
        `https://6371e259025414c637002627.mockapi.io/api/fiddle/users`,
        {
          headers: {
            Authorization: `Bearer ${cookies.jwt}`,
          },
        }
      );
      users = data;
      console.log(data);
    } catch (e) {
      console.log(e);
    }
  }

  if (!users) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }

  return {
    props: { users },
  };
};

export default Profile;
