import React from "react";
import axios from "axios";
import nookies from "nookies";
import Head from "next/head";
import NavBar from "../../components/navigation/NavBar";
import { useRouter } from "next/router";
import Link from "next/link";
import { FormContent, FormTitle } from "../../components/formstyles";
import { Box, Typography } from "@mui/material";

const Profile = ({ users }) => {
  const router = useRouter();
  const id = router.query.id as string;
  return (
    <>
      <Head>
        <title>Profile - Development Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <FormTitle>Users</FormTitle>
      <Box
        sx={{
          marginTop: 2,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
        }}
      >
        {users?.map((user) => (
          <Typography key={user.id}>
            <Link href={`/profile/${user.id}`}>{user.username}</Link>
          </Typography>
        ))}
      </Box>
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  const cookies = nookies.get(ctx);
  let users = null;

  if (cookies?.jwt) {
    try {
      const { data } = await axios.get(
        `https://6371e259025414c637002627.mockapi.io/api/fiddle/users`
      );
      users = data;
      console.log(data);
    } catch (e) {
      console.log(e);
    }
  }

  if (
    cookies?.LoginStatus === "false" ||
    !cookies?.LoginStatus ||
    !cookies?.jwt
  ) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }

  return {
    props: { users },
  };

  revalidate: 10;
};

export default Profile;
