import Head from "next/head";
import React from "react";
import { ContactForm } from "../components/form-fields/ContactForm";
import NavBar from "../components/navigation/NavBar";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact - Development Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <ContactForm />
    </>
  );
};

export default Contact;
