import Head from "next/head";
import axios from "axios";
import NavBar from "../components/navigation/NavBar";

export default function Home({ activeUser }) {
  return (
    <>
      <Head>
        <title>Home - Development Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {/* {activeUser.map((user: any) => (
        <div key={user.id} className="capitalized">
          Welcome {`${user.firstName} ${user.lastName}`}!
        </div>
      ))} */}
    </>
  );
}
