import Head from "next/head";
import axios from "axios";
import NavBar from "../components/navigation/NavBar";
import { Container } from "../components/sharedstyles";
import { FormContent, FormTitle } from "../components/formstyles";

export default function Home({ activeUser }) {
  return (
    <>
      <Head>
        <title>Home - Development Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Container>
        <FormTitle>Home</FormTitle>
        <FormContent>Sample</FormContent>
      </Container>
    </>
  );
}
