import axios from "axios";
import Head from "next/head";
import React from "react";
import nookies from "nookies";
import { LoginForm } from "../components/form-fields/LoginForm";

const Login = () => {
  return (
    <>
      <Head>
        <title>Login - Development Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginForm />
    </>
  );
};

const updateIsLogin = async (e: boolean) => {
  await axios.put(
    "https://6371e259025414c637002627.mockapi.io/api/fiddle/users",
    {
      isLogin: e,
    }
  );
};

export const getServerSideProps = async (ctx: any) => {
  const cookies = nookies.get(ctx);
  let user = null;
  if (cookies?.jwt) {
    try {
      const { data } = await axios.get(
        `https://6371e259025414c637002627.mockapi.io/api/fiddle/users`,
        {
          headers: {
            Authorization: `Bearer ${cookies.jwt}`,
          },
        }
      );
      user = data;
    } catch (e) {
      console.log(e);
    }
  }

  if (user) {
    return {
      redirect: {
        permanent: false,
        destination: "/profile",
      },
    };
  }

  return {
    props: {},
  };
};

export default Login;
