import Head from "next/head";
import React from "react";
import axios from "axios";
import nookies from "nookies";
import { RegistrationForm } from "../components/form-fields/RegistrationForm";

const Register = () => {
  return (
    <>
      <Head>
        <title>Register - Development Exercise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegistrationForm />
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  const cookies = nookies.get(ctx);
  let users = null;
  if (cookies?.jwt) {
    try {
      const { data } = await axios.get(
        `https://6371e259025414c637002627.mockapi.io/api/fiddle/users`,
        {
          headers: {
            Authorization: `Bearer ${cookies.jwt}`,
          },
        }
      );
      users = data;
    } catch (e) {
      console.log(e);
    }
  }

  if (users) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }

  return {
    props: {},
  };
};

export default Register;
